### ISSUE TITLE
Weird log/lin specifications in Chen2009

### ISSUE THREAD

**Issue by FFroehlich** [Benchmarking-Initiative/Benchmark-Models-PEtab#106]
I'm having difficulties optimizing the Chen2009 problem. After some investigations, I realized that there are a couple (arbitrary?) parameters that are specified to be on linear scale (see https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/master/Benchmark-Models/Chen_MSB2009/parameters_Chen_MSB2009.tsv) with negative boundaries, even though they are used in mass action kinetics. I suspect this is what's causing integration issues.

I find this a bit surprising since in the original adjoin paper, all parameter were estimated on a log scale and estimation seemed to have worked. I cannot find any specific information about what was done in the MATLAB Benchmark paper.

Is there any further information why this problem was specified as is?

**Comment by elbaraim** [comment]
Hi @FFroehlich 
I implemented that model in the Benchmark collection. I will have a look at the model, probably it is a mistake (the parameter scales as they are now).

Thanks for reporting the issue!

**Comment by elbaraim** [comment]
Another thing that needs to be checked [here](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/issues/21#issuecomment-768217641)

**Comment by elbaraim** [comment]
addressed in #107

**Comment by elbaraim** [comment]
Hi @FFroehlich 

We have just noticed that some of the nominal values are zero (as they are defined in the original publication and in the PESTO example).

How should we handle those?
1) setting them to very small values, e.g., 1e-15, and adapt the boundaries (this is done in PESTO)
2) fitting them in linear scale with lower bound set to zero (hopefully fixing the bad numerics)

**Comment by JanHasenauer** [comment]
Were these parameters fitted in the original example? if not, i would set them to zero and not estimate them.

**Comment by elbaraim** [comment]
Hi @JanHasenauer 
in the original publication the statement that i found regarding these zero parameters is the following:
`Rates that are 0 participate in regulation reactions that may be turned on/off for testing hypotheses`

I am not sure how to interpret this...

**Comment by FFroehlich** [comment]
Thanks for following this up. To me it sounds reasonable to set them to zero on a linear scale and not estimate them. 

How was this handled in the Hass2019 benchmark? Do the reference values in the petab file correspond to the best parameters found in Hass2019 or the values from the original publication?
It sounds like it would be helpful to document such pecularities in a readme file in the respective model directory.

**Comment by elbaraim** [comment]
> How was this handled in the Hass2019 benchmark? 

In the benchmark paper these were estimated in linear scale with the bounds present in the current PEtab version of this model.

> Do the reference values in the petab file correspond to the best parameters found in Hass2019 or the values from the original publication?

The reference values as far as I can see they are the same as in the PESTO implementation. Therefore I assume the same as in the original publication (?). If needed, I could try to check them (the publication values).

**Comment by FFroehlich** [comment]
As far as I can tell 

> > How was this handled in the Hass2019 benchmark?
> 
> In the benchmark paper these were estimated in linear scale with the bounds present in the current PEtab version of this model (the current version in `master` branch).
> 

I just had a brief look at the matlab results and in the multistart results, there is a large number of parameter that is set to 0. Also my matlab/d2d skills are a bit rusty, but the d2d contains the following line `ar.qFit(ar.p==0 & ar.qLog10==0) = 2;`, which looks like estimation is disabled for everything that is on a log scale or has zero nominal value. Are you sure those parameters were estimated in the original benchmark?

**Comment by elbaraim** [comment]
Thanks for having the detailed look. Now I am not sure anymore 😓 

Looks like Helge defined the fixing of these parameters (see git history), therefore we could assume these were fixed for the results presented in the benchmark paper (?). I do not know. Still, it is funny that is set to `2` while d2d docs read
`Vector of logicals whether parameter is fixed (0) or fitted (1)` 

I guess since it is **not** `==1` is then handled as fixed. And as this is the current version in the `master` from d2d we could take it as final & valid (?)

**Comment by LeonardSchmiester** [comment]
> Thanks for having the detailed look. Now I am not sure anymore sweat
> 
> Looks like Helge defined the fixing of these parameters (see git history), therefore we could assume these were fixed for the results presented in the benchmark paper (?). I do not know. Still, it is funny that is set to `2` while d2d docs read
> `Vector of logicals whether parameter is fixed (0) or fitted (1)`
> 
> I guess since it is **not** `==1` is then handled as fixed. And as this is the current version in the `master` from d2d we could take it as final & valid (?)

From the D2D code it reads `% qFit      0=fixed, 1=fitted, 2=constant`. Not sure, what the difference between fixed and constant is here. But I guess it's correct to set `estimate=0` for these parameters then.
