### ISSUE TITLE
Model Oliveira_Nat2021

### ISSUE THREAD

**Issue by lorenapohl** [Benchmarking-Initiative/Benchmark-Models-PEtab#121]
I implemented the Oliveira et al model for the entire state Bahia, Brazil and for the interior cities.
https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/pull/120

The main difference in the models is that on the state-wide level there is data available on the occupied hospital and ICU beds. For the interior cities only the cases and deaths are included as observables. Also, on the state-wide level the authors estimated the transmission rate as a piecewise constant function, one time with two pieces and once with three pieces. In my implementation I added the parameter `beta_2_multiplier` which can be set to 0 in the conditions table if the transmission rate should be a two-piece function and set to 1 if it should be a three-piece function. 

Some of the figures for the state-wide model from the paper can not be fully reproduced because the authors don't provide their estimates for the initial number of people in each compartment. For the interior, these estimates are in this table from the paper's GitHub repo:
https://github.com/cidacslab/Mathematical-and-Statistical-Modeling-of-COVID19-in-Brazil/blob/master/Reproducibility%20of%20published%20results/Evaluating%20the%20burden%20of%20COVID-19%20in%20Bahia%2C%20Brazil:%20A%20modeling%20analysis%20of%2014.8%20million%20individuals/results/Interior/Parameters.csv

**Comment by dilpath** [comment]
added in #120
