### ISSUE TITLE
citation/reference to original models

### ISSUE THREAD

**Issue by anandijain** [Benchmarking-Initiative/Benchmark-Models-PEtab#128]
in the pursuit of reproducibility, it would be great to have some information about each model (like citation and link to original SBML model) 

currently there does not seem to be a way to find out where a given model came from. 

thanks

**Comment by paulflang** [comment]
+1. I think a BioModels download url would be good (although I assume you had to make some modifications for PEtab compatibility).

**Comment by dweindl** [comment]
Hi @anandijain, the DOI of the original publication should already be included in the SBML annotations, for example: https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/c9bfb921b4363ac41c6cc53c068bd6f7088e1a69/Benchmark-Models/Alkan_SciSignal2018/model_Alkan_SciSignal2018.xml#L30
