### ISSUE TITLE
Machine readable model property overview

### ISSUE THREAD

**Issue by FFroehlich** [Benchmarking-Initiative/Benchmark-Models-PEtab#169]
Would be nice to have the table provided in README.md in some machine readable format like `.csv` or `.tsv`.

**Comment by dweindl** [comment]
Only requires saving this `DataFrame` as csv/tsv https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/11dfed1e44286f10ce936a2524bb06b39855a525/scripts/overview.py#L113

**Comment by FFroehlich** [comment]
> Only requires saving this `DataFrame` as csv/tsv
> 
> https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/11dfed1e44286f10ce936a2524bb06b39855a525/scripts/overview.py#L113

okay, maybe it makes sense to expose that function in the python package :)
