### ISSUE TITLE
why is Laske called Laske?

### ISSUE THREAD

**Issue by FFroehlich** [Benchmarking-Initiative/Benchmark-Models-PEtab#171]
According to model metadata it was adapted from https://www.ebi.ac.uk/biomodels/MODEL1307270000, i.e., https://pubmed.ncbi.nlm.nih.gov/22593159/

I can't find any 2019 publication by Laske in PLoS Comp Bio

**Comment by C-Peiter** [comment]
It's called Laske, because it was related to issue #83. Yes, the model was adapted from Heldt et al. and there's also an issue for that (#76).

**Comment by FFroehlich** [comment]
Okay thanks, makes sense, but then the respective references in https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/master/README.md are wrong. Would also be nice to include a bit more provenance information in these benchmarks.

**Comment by dilpath** [comment]
Closed in #173 and #189
