### ISSUE TITLE
Wrong paper reference for Froehlich_CellSystems2018

### ISSUE THREAD

**Issue by dweindl** [Benchmarking-Initiative/Benchmark-Models-PEtab#203]
In https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/master/Benchmark-Models/Froehlich_CellSystems2018/model_Froehlich_CellSystems2018.xml

correct one: https://doi.org/10.1016/j.cels.2018.10.013

**Comment by dilpath** [comment]
closed in #204
