### ISSUE TITLE
new format for Chen

### ISSUE THREAD

**Issue by elbaraim** [Benchmarking-Initiative/Benchmark-Models-PEtab#21]

**Comment by LeonardSchmiester** [comment]
@elbaraim Any updates here?

**Comment by LeonardSchmiester** [comment]
Did you have a chance to look into this @elbaraim ? Should be just exchanging the data and simulating to see if the results fit, right?

**Comment by dweindl** [comment]
*ping* @elbaraim

**Comment by elbaraim** [comment]
Apparently there is a bug in the visualization file, @erikadudki could you have a look?

**Comment by erikadudki** [comment]
fixed it :+1:

**Comment by elbaraim** [comment]
reopened: see #106

**Comment by elbaraim** [comment]
When looking at the issue #106 

I also found that in the [original Benchmark collection](https://github.com/Benchmarking-Initiative/Benchmark-Models/tree/master/Benchmark-Models/Chen_MSB2009/SBML) some parameters "got lost" during the initial SBML export. Therefore, also missing in the PEtab implementation.

These are: `KD_iressa_mt`, `KD_iressa_wt`, `k98`, `k99` and `k100`.

This is weird, since these parameters appear in the d2d model file, e.g., [KD_iressa_wt](https://github.com/Data2Dynamics/d2d/blob/396622f20bbbc2f49a16a29d1d5ad34ebcf63c83/arFramework3/Examples/Chen_MSB2009/Models/model_ChenMSB2009.def#L1180) (already checked for the others).

I will keep on looking and post an update ASAP.

**Comment by elbaraim** [comment]
Additionally these parameters from the [original paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2644173/)
`k10`, `Kinh2`, `Kinh3`, `Kinh4`, `Ks`, `k13`, `k14`, `k22b`, `k28b`, `k16b`, `k34b`, `k3`, `KD_ATP`, `KD`, `k121`, `kd_v853`
do not appear in the current implementation.

However I checked all of them and they do **not** have any role in the original model (publication). They only appear in the list of parameters.

So I think it is fine that they do not appear, 
any contrary thoughts on this? @LeonardSchmiester

**Comment by LeonardSchmiester** [comment]
> Additionally these parameters from the [original paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2644173/)
> `k10`, `Kinh2`, `Kinh3`, `Kinh4`, `Ks`, `k13`, `k14`, `k22b`, `k28b`, `k16b`, `k34b`, `k3`, `KD_ATP`, `KD`, `k121`, `kd_v853`
> do not appear in the current implementation.
> 
> However I checked all of them and they do **not** have any role in the original model (publication). They only appear in the list of parameters.
> 
> So I think it is fine that they do not appear,
> any contrary thoughts on this? @LeonardSchmiester

So they are defined as parameters in the original SBML model but don't occur in any reactions etc.?! If they are not used in any context I guess it should be fine to not have them in the model

**Comment by elbaraim** [comment]
> > Additionally these parameters from the [original paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2644173/)
> > `k10`, `Kinh2`, `Kinh3`, `Kinh4`, `Ks`, `k13`, `k14`, `k22b`, `k28b`, `k16b`, `k34b`, `k3`, `KD_ATP`, `KD`, `k121`, `kd_v853`
> > do not appear in the current implementation.
> > However I checked all of them and they do **not** have any role in the original model (publication). They only appear in the list of parameters.
> > So I think it is fine that they do not appear,
> > any contrary thoughts on this? @LeonardSchmiester
> 
> So they are defined as parameters in the original SBML model but don't occur in any reactions etc.?! If they are not used in any context I guess it should be fine to not have them in the model

Exactly. They **only** appear in the list of parameters.

**Comment by LeonardSchmiester** [comment]
> When looking at the issue #106
> 
> I also found that in the [original Benchmark collection](https://github.com/Benchmarking-Initiative/Benchmark-Models/tree/master/Benchmark-Models/Chen_MSB2009/SBML) some parameters "got lost" during the initial SBML export. Therefore, also missing in the PEtab implementation.
> 
> These are: `KD_iressa_mt`, `KD_iressa_wt`, `k98`, `k99` and `k100`.
> 
> This is weird, since these parameters appear in the d2d model file, e.g., [KD_iressa_wt](https://github.com/Data2Dynamics/d2d/blob/396622f20bbbc2f49a16a29d1d5ad34ebcf63c83/arFramework3/Examples/Chen_MSB2009/Models/model_ChenMSB2009.def#L1180) (already checked for the others).
> 
> I will keep on looking and post an update ASAP.

Where these parameters also in the original model from the publication? Could it be, that they are somehow replaced with other expressions in D2D?

**Comment by elbaraim** [comment]
> > When looking at the issue #106
> > I also found that in the [original Benchmark collection](https://github.com/Benchmarking-Initiative/Benchmark-Models/tree/master/Benchmark-Models/Chen_MSB2009/SBML) some parameters "got lost" during the initial SBML export. Therefore, also missing in the PEtab implementation.
> > These are: `KD_iressa_mt`, `KD_iressa_wt`, `k98`, `k99` and `k100`.
> > This is weird, since these parameters appear in the d2d model file, e.g., [KD_iressa_wt](https://github.com/Data2Dynamics/d2d/blob/396622f20bbbc2f49a16a29d1d5ad34ebcf63c83/arFramework3/Examples/Chen_MSB2009/Models/model_ChenMSB2009.def#L1180) (already checked for the others).
> > I will keep on looking and post an update ASAP.
> 
> Where these parameters also in the original model from the publication? Could it be, that they are somehow replaced with other expressions in D2D?

These parameters indeed appear in the original model from the publication. Regarding the replacement thing, this is what I am trying to check atm :)

**Comment by elbaraim** [comment]
> > > When looking at the issue #106
> > > I also found that in the [original Benchmark collection](https://github.com/Benchmarking-Initiative/Benchmark-Models/tree/master/Benchmark-Models/Chen_MSB2009/SBML) some parameters "got lost" during the initial SBML export. Therefore, also missing in the PEtab implementation.
> > > These are: `KD_iressa_mt`, `KD_iressa_wt`, `k98`, `k99` and `k100`.
> > > This is weird, since these parameters appear in the d2d model file, e.g., [KD_iressa_wt](https://github.com/Data2Dynamics/d2d/blob/396622f20bbbc2f49a16a29d1d5ad34ebcf63c83/arFramework3/Examples/Chen_MSB2009/Models/model_ChenMSB2009.def#L1180) (already checked for the others).
> > > I will keep on looking and post an update ASAP.
> > 
> > 
> > Where these parameters also in the original model from the publication? Could it be, that they are somehow replaced with other expressions in D2D?
> 
> These parameters indeed appear in the original model from the publication. Regarding the replacement thing, this is what I am trying to check atm :)

So I have checked the model compilation and these parameters are removed in the symbolic expressions, then I guess the replacement that you mentioned is taking place (as I said, they appear in the model definition file). Seems fine then.

I will continue then with the issue regarding the parameter scales. Do you agree @LeonardSchmiester ?

**Comment by LeonardSchmiester** [comment]
> I will continue then with the issue regarding the parameter scales. Do you agree @LeonardSchmiester ?

Yes, sounds good.

**Comment by FFroehlich** [comment]
Whats the status here?
