### ISSUE TITLE
Additional Model: Blasi et al. , Cell Systems, 2016

### ISSUE THREAD

**Issue by elbaraim** [Benchmarking-Initiative/Benchmark-Models-PEtab#24]

**Comment by LeonardSchmiester** [comment]
@elbaraim When you implemented the model, did you check if the simulations match the publication?

**Comment by LeonardSchmiester** [comment]
Simulations look better now. Optimization also seems to work (and gives better LLH values than with the nominal parameters)

**Comment by LeonardSchmiester** [comment]
Fixed by #69
