### ISSUE TITLE
FiedlerBMC2016 steady state incorrect

### ISSUE THREAD

**Issue by m-philipps** [Benchmarking-Initiative/Benchmark-Models-PEtab#242]
According to the paper, the initial condition is supposed to be the analytically derived steady state, however, simulating the SBML model in COPASI produces state trajectories with non-zero gradients.
![image](https://github.com/user-attachments/assets/3eb22e54-77c2-4530-a4ff-6eca35d02e4d)

The analytical expression for the steady state in the paper is given for the reformulated model, but implementing the reformulated model also resulted in an incorrect steady state. The expressions are rather complex (Supplemental Material S1, equation 10) so there might be a mistake in the official benchmark collection model, [my re-implementation](https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/blob/463333c70140c0495a0d863445aab780b37c8e19/Benchmark-Models/Fiedler_BMCSystBiol2016/reformulated/model.xml), or the paper supplement.
![image](https://github.com/user-attachments/assets/7e40f317-9ad5-4c79-83ed-3b78b5567aae)

**Comment by dilpath** [comment]
In this notebook, the steady-states are computed and inserted into SBML, with [sbmlmath](https://github.com/dweindl/sbmlmath).

When I check the new SBML in COPASI however, the simulations do not appear steady :shrug: I can take a look later when I have time again.
[fiedler_steady_state.zip](https://github.com/user-attachments/files/17366734/fiedler_steady_state.zip)

**Comment by JanHasenauer** [comment]
Steady states of the system is defined for k1max = k10 and seems to be valid. For t > 0, the value of k1max changes. This changes models a time-dependent input.

I simulated the model for the case k1max = k10 (by setting k11 = 0). The steady steady seems to be correct.

**Comment by m-philipps** [comment]
Thanks, can confirm that setting `k11` to $0$ fixes it in the reformulated model as well.
