### ISSUE TITLE
Visualization files for all models (list)

### ISSUE THREAD

**Issue by MerktSimon** [Benchmarking-Initiative/Benchmark-Models-PEtab#28]
This issue serves as an overview of which models already have the visualization file. During the work on each model this model's issue should be re-opened. Once all models have one this can be closed.

Models which already have a visualization file:
- Isensee
- Chen
- Fujita
- Swameye_PNAS2003
- Boehm
- Bruno_JExpBio2016
- Raia_CancerResearch2011

**Comment by dilpath** [comment]
> Can this be merged/consolidated with issue #156?

Yes, thanks for the contributions from everyone so far
