### ISSUE TITLE
Validate Alkan model

### ISSUE THREAD

**Issue by LeonardSchmiester** [Benchmarking-Initiative/Benchmark-Models-PEtab#44]
Import and simulation works.

@LaraFuhrmann Did you validate if the simulations match the ones from the publication? Could you create a visualization file for this?

**Comment by LaraFuhrmann** [comment]
So far I only simulated the default conditions of the model, and changed them manually to compare to the plots in the paper. Those results matched. 

Is there a standard way to generate the simulationData-file with the simulations for all the conditions (there are around 90 experimental conditions in this model)?

**Comment by LeonardSchmiester** [comment]
> Is there a standard way to generate the simulationData-file with the simulations for all the conditions (there are around 90 experimental conditions in this model)?

Yes. After simulating the model with `simulations = simulate_petab(petab_problem=petab_problem, amici_model=amici_model)` (`from amici.petab_objective import simulate_petab`)

you can create a simulation data file with amicis `rdatas_to_measurement_df` (`from amici.petab_objective import rdatas_to_measurement_df`), by running 

```
sim_df = rdatas_to_measurement_df(simulations['rdatas'], amici_model, petab_problem.measurement_df)
sim_df.to_csv('simulated_data.tsv', sep='\t')
```

**Comment by LeonardSchmiester** [comment]
Thanks for creating the vis file @LaraFuhrmann 
If the model is working and you confirmed, that you can reproduce the figures in the respective paper, feel free to do a pull request into the master.
