### ISSUE TITLE
Fix Schwen_PONE2014

### ISSUE THREAD

**Issue by LeonardSchmiester** [Benchmarking-Initiative/Benchmark-Models-PEtab#48]
I cannot reproduce simulations from the original Benchmark Collection. @elbaraim you implemented the model right? Could you check this?

**Comment by dweindl** [comment]
*ping* @elbaraim

**Comment by elbaraim** [comment]
what exactly you cannot reproduce? the simulated trajectories? @LeonardSchmiester

**Comment by LeonardSchmiester** [comment]
Yes the simulated data from the old benchmark repository.

**Comment by JanHasenauer** [comment]
The original implementation is in D2D. Might be good to compare to this.
