### ISSUE TITLE
Fix Isensee model

### ISSUE THREAD

**Issue by LeonardSchmiester** [Benchmarking-Initiative/Benchmark-Models-PEtab#54]
I can currently not simulate the model with AMICI because of: `At t = 60, mxstep steps taken before reaching tout`

Increasing max steps didn't help so far.

**Comment by JanHasenauer** [comment]
I never simulated the model in AMICI. Numerical simulations in D2D were never problematic.

**Comment by JanHasenauer** [comment]
Did you try to simulate a subset of the conditions are check whether the results agree for those?

**Comment by LeonardSchmiester** [comment]
Not yet. Will have a look

**Comment by JanHasenauer** [comment]
As this is the visualization example used by PEtab, it would be rather valuable if this is working
