### ISSUE TITLE
Finish Bachmann

### ISSUE THREAD

**Issue by LeonardSchmiester** [Benchmarking-Initiative/Benchmark-Models-PEtab#56]
Needs to be checked. So far I was not able to reproduce xi2 / llh values from original benchmark collection

**Comment by LeonardSchmiester** [comment]
ActD, CISoe, SOCS3oe are not correctly implemented (appear as parameters but not in the reactions etc. in the SBML model).

**Comment by elbaraim** [comment]
@LeonardSchmiester  should I try to export the model from d2d?

**Comment by LeonardSchmiester** [comment]
Thanks. I think I fixed it. But you can review my pull request @elbaraim
