### ISSUE TITLE
Add Fröhlich et al. (2018)

### ISSUE THREAD

**Issue by JanHasenauer** [Benchmarking-Initiative/Benchmark-Models-PEtab#78]
https://www.cell.com/cell-systems/pdfExtended/S2405-4712(18)30438-1

**Comment by dweindl** [comment]
Mostly here: https://github.com/ICB-DCM/CS_Signalling_ERBB_RAS_AKT. May need to be double-checked.

**Comment by LeonardSchmiester** [comment]
We have a similar issue here as in #77. Originally simulations of drug treatments were divided by control simulations. Should we also implement this with scalings (as in the hierarchical paper)?
This was also already done in https://github.com/ICB-DCM/CS_Signalling_ERBB_RAS_AKT
However then we do not really have nominal values for the scaling parameters.

**Comment by JanHasenauer** [comment]
Yes, I would go for this

**Comment by JanHasenauer** [comment]
Might be good to also implemented Schmiester et al 2019 than also as it adds the proteomics data.
