### ISSUE TITLE
Add Bertozzi et al. (2020)

### ISSUE THREAD

**Issue by vanako** [Benchmarking-Initiative/Benchmark-Models-PEtab#99]
https://www.pnas.org/content/117/29/16732

**Comment by dilpath** [comment]
SIR model trained on 10 days of New York and California data from the COVID-19 pandemic (March 2020).

The published model is defined in the paper as two versions: with and without a reparameterization. The implementation in this collection has model dynamics defined in terms of a standard SIR model, but $\beta$ is calculated from the parameters in the PEtab parameter table as $\beta = \frac{R_0 \gamma}{N}$.

Table 1 in the original publication suggests that 10 days of data were used for training, which matches the implementation in this collection.

The model is generally easy to train, to produce a fit of similar quality to the paper. 1000 starts with SciPy L-BFGS-B were use to produce the optimized parameter vector (nominal values in the parameter table) and corresponding `simulations.tsv`. However, even 10 starts will produce similarly good fits.

The paper uses difference equations for their simulation [1] of the ODE system, which may produce differences compared to ODE solvers typically used with SBML/PEtab.

Updated in #222 

[1] https://github.com/gomohler/pnas2020/blob/master/sir.R

**Comment by dilpath** [comment]
The paper uses a likelihood based on the Poisson distribution, unlike the Gaussian distribution in the implementation here.

However, Poisson $\approx$ Gaussian when the parameter is large, so the implementation here is still capable of producing a good fit (as reported above).

The original implementation also drops the constant $\frac{1}{y!}$ in the Poisson distribution, where $y$ is the observed count of infection or death.
https://github.com/gomohler/pnas2020/blob/cb98dfc292702a2e3de0d6aaa0366b7fc7c62fc8/model_compare.R#L95
